<?php

$dir = __DIR__ . '/items';

$items = array_merge(
    require $dir . '/weapons.php',
    require $dir . '/helmets.php',
    require $dir . '/armor.php',
    require $dir . '/gloves.php',
    require $dir . '/boots.php',
    require $dir . '/belts.php',
    require $dir . '/rings.php',
    require $dir . '/amulets.php',
    require $dir . '/potions.php'
);

$assetKeys = [
    'beginner-sword',
    'iron-sword',
    'steel-sword',
    'rune-sword',
    'dragon-fang-sword',
    'titan-sword',
    'paladin-sword',
    'berserker-sword',
    'angel-sword',
    'holy-judgment-sword',
    'god-king-sword',
    'eternal-blade-sword',
    'chaos-cleaver-sword',
    'beginner-staff',
    'oak-staff',
    'crystal-staff',
    'moon-staff',
    'star-staff',
    'void-staff',
    'arcane-staff',
    'phoenix-staff',
    'angel-staff',
    'archmage-staff',
    'divine-revelation-staff',
    'eternal-mana-source-staff',
    'chaos-wand',
    'beginner-bow',
    'long-bow',
    'elf-bow',
    'demon-hunter-bow',
    'shadow-bow',
    'wind-god-bow',
    'elf-king-bow',
    'phoenix-feather-bow',
    'angel-bow',
    'marksman-bow',
    'divine-hunter-bow',
    'eternal-hunter-bow',
    'chaos-piercer-bow',
    'cloth-cap-helmet',
    'leather-cap-helmet',
    'iron-helmet',
    'mithril-helmet',
    'dragon-bone-helmet',
    'holy-helmet',
    'paladin-helmet',
    'angel-helmet',
    'divine-helmet',
    'eternal-helmet',
    'chaos-helmet',
    'creation-helmet',
    'god-king-helmet',
    'cloth-robe-armor',
    'leather-armor',
    'chain-mail-armor',
    'plate-armor',
    'mithril-armor',
    'dragon-scale-armor',
    'divine-armor',
    'paladin-armor',
    'angel-armor',
    'holy-armor',
    'eternal-armor',
    'chaos-armor',
    'creation-armor',
    'god-king-armor',
    'cloth-gloves',
    'leather-gloves',
    'iron-gauntlets',
    'steel-gauntlets',
    'dragon-skin-gloves',
    'power-gloves',
    'paladin-gloves',
    'angel-gloves',
    'divine-gloves',
    'eternal-gloves',
    'chaos-gloves',
    'creation-gloves',
    'god-king-gloves',
    'cloth-boots',
    'leather-boots',
    'iron-boots',
    'swift-boots',
    'ranger-boots',
    'phantom-boots',
    'paladin-boots',
    'angel-boots',
    'god-speed-boots',
    'eternal-boots',
    'chaos-boots',
    'creation-boots',
    'god-king-boots',
    'cloth-belt',
    'leather-belt',
    'iron-belt',
    'giant-belt',
    'life-belt',
    'titan-belt',
    'paladin-belt',
    'angel-belt',
    'divine-belt',
    'eternal-belt',
    'chaos-belt',
    'creation-belt',
    'god-king-belt',
    'copper-ring',
    'silver-ring',
    'gold-ring',
    'ruby-ring',
    'sapphire-ring',
    'jade-ring',
    'raven-ring',
    'stone-of-jordan-ring',
    'dwarf-ring',
    'magic-ring',
    'paladin-ring',
    'angel-ring',
    'divine-ring',
    'eternal-ring',
    'chaos-ring',
    'creation-ring',
    'god-king-ring',
    'wooden-amulet',
    'bone-amulet',
    'crystal-amulet',
    'lion-amulet',
    'cat-eye-amulet',
    'marshal-amulet',
    'infernal-amulet',
    'sacred-amulet',
    'paladin-amulet',
    'angel-amulet',
    'sacred-angel-amulet',
    'eternal-amulet',
    'chaos-amulet',
    'creation-amulet',
    'god-king-amulet',
    'light-health-potion',
    'health-potion',
    'greater-health-potion',
    'super-health-potion',
    'light-mana-potion',
    'mana-potion',
    'greater-mana-potion',
    'super-mana-potion',
];

return array_map(
    fn (array $item, int $index) => array_merge($item, [
        'asset_key' => $assetKeys[$index],
    ]),
    $items,
    array_keys($items)
);
