<?php

$monsters = [
    [
        'name' => '小野猪',
        'type' => 'normal',
        'level' => 1,
        'hp_base' => 30,
        'attack_base' => 3,
        'defense_base' => 1,
        'experience_base' => 10,
    ],
    [
        'name' => '野狼',
        'type' => 'normal',
        'level' => 2,
        'hp_base' => 40,
        'attack_base' => 5,
        'defense_base' => 2,
        'experience_base' => 15,
    ],
    [
        'name' => '森林哥布林',
        'type' => 'normal',
        'level' => 3,
        'hp_base' => 70,
        'attack_base' => 10,
        'defense_base' => 4,
        'experience_base' => 20,
    ],
    [
        'name' => '巨狼',
        'type' => 'elite',
        'level' => 5,
        'hp_base' => 150,
        'attack_base' => 15,
        'defense_base' => 6,
        'experience_base' => 50,
    ],
    [
        'name' => '树人长老',
        'type' => 'boss',
        'level' => 8,
        'hp_base' => 400,
        'attack_base' => 25,
        'defense_base' => 12,
        'experience_base' => 150,
    ],
    [
        'name' => '野猪王',
        'type' => 'elite',
        'level' => 6,
        'hp_base' => 200,
        'attack_base' => 20,
        'defense_base' => 8,
        'experience_base' => 70,
    ],
    [
        'name' => '蝙蝠',
        'type' => 'normal',
        'level' => 5,
        'hp_base' => 45,
        'attack_base' => 12,
        'defense_base' => 3,
        'experience_base' => 25,
    ],
    [
        'name' => '洞穴蜘蛛',
        'type' => 'normal',
        'level' => 6,
        'hp_base' => 55,
        'attack_base' => 14,
        'defense_base' => 4,
        'experience_base' => 30,
    ],
    [
        'name' => '骷髅兵',
        'type' => 'normal',
        'level' => 7,
        'hp_base' => 80,
        'attack_base' => 16,
        'defense_base' => 8,
        'experience_base' => 40,
    ],
    [
        'name' => '骷髅法师',
        'type' => 'elite',
        'level' => 10,
        'hp_base' => 200,
        'attack_base' => 25,
        'defense_base' => 10,
        'experience_base' => 80,
    ],
    [
        'name' => '骸骨之王',
        'type' => 'boss',
        'level' => 12,
        'hp_base' => 600,
        'attack_base' => 35,
        'defense_base' => 18,
        'experience_base' => 250,
    ],
    [
        'name' => '巨型蜘蛛',
        'type' => 'elite',
        'level' => 8,
        'hp_base' => 180,
        'attack_base' => 22,
        'defense_base' => 9,
        'experience_base' => 65,
    ],
    [
        'name' => '小恶魔',
        'type' => 'normal',
        'level' => 12,
        'hp_base' => 100,
        'attack_base' => 25,
        'defense_base' => 10,
        'experience_base' => 60,
    ],
    [
        'name' => '火焰元素',
        'type' => 'normal',
        'level' => 14,
        'hp_base' => 120,
        'attack_base' => 30,
        'defense_base' => 12,
        'experience_base' => 80,
    ],
    [
        'name' => '地狱骑士',
        'type' => 'elite',
        'level' => 16,
        'hp_base' => 350,
        'attack_base' => 40,
        'defense_base' => 20,
        'experience_base' => 150,
    ],
    [
        'name' => '地狱魔王',
        'type' => 'boss',
        'level' => 20,
        'hp_base' => 1000,
        'attack_base' => 60,
        'defense_base' => 30,
        'experience_base' => 500,
    ],
    [
        'name' => '炎魔',
        'type' => 'elite',
        'level' => 18,
        'hp_base' => 400,
        'attack_base' => 50,
        'defense_base' => 22,
        'experience_base' => 180,
    ],
    [
        'name' => '恶魔巫师',
        'type' => 'elite',
        'level' => 19,
        'hp_base' => 320,
        'attack_base' => 55,
        'defense_base' => 15,
        'experience_base' => 160,
    ],
    [
        'name' => '深渊魔虫',
        'type' => 'normal',
        'level' => 22,
        'hp_base' => 180,
        'attack_base' => 55,
        'defense_base' => 25,
        'experience_base' => 150,
    ],
    [
        'name' => '暗影幽灵',
        'type' => 'normal',
        'level' => 24,
        'hp_base' => 200,
        'attack_base' => 60,
        'defense_base' => 20,
        'experience_base' => 180,
    ],
    [
        'name' => '虚空行者',
        'type' => 'elite',
        'level' => 26,
        'hp_base' => 600,
        'attack_base' => 80,
        'defense_base' => 35,
        'experience_base' => 300,
    ],
    [
        'name' => '深渊领主',
        'type' => 'boss',
        'level' => 30,
        'hp_base' => 2000,
        'attack_base' => 120,
        'defense_base' => 60,
        'experience_base' => 1000,
    ],
    [
        'name' => '天使卫士',
        'type' => 'normal',
        'level' => 32,
        'hp_base' => 300,
        'attack_base' => 90,
        'defense_base' => 45,
        'experience_base' => 300,
    ],
    [
        'name' => '炽天使',
        'type' => 'normal',
        'level' => 35,
        'hp_base' => 350,
        'attack_base' => 100,
        'defense_base' => 50,
        'experience_base' => 350,
    ],
    [
        'name' => '天使长',
        'type' => 'elite',
        'level' => 38,
        'hp_base' => 900,
        'attack_base' => 130,
        'defense_base' => 70,
        'experience_base' => 600,
    ],
    [
        'name' => '堕落天使',
        'type' => 'elite',
        'level' => 42,
        'hp_base' => 1100,
        'attack_base' => 150,
        'defense_base' => 80,
        'experience_base' => 750,
    ],
    [
        'name' => '大天使长',
        'type' => 'boss',
        'level' => 45,
        'hp_base' => 3500,
        'attack_base' => 200,
        'defense_base' => 100,
        'experience_base' => 2000,
    ],
    [
        'name' => '圣殿骑士',
        'type' => 'elite',
        'level' => 40,
        'hp_base' => 1000,
        'attack_base' => 140,
        'defense_base' => 90,
        'experience_base' => 680,
    ],
    [
        'name' => '神仆',
        'type' => 'normal',
        'level' => 48,
        'hp_base' => 500,
        'attack_base' => 160,
        'defense_base' => 80,
        'experience_base' => 500,
    ],
    [
        'name' => '神使',
        'type' => 'normal',
        'level' => 52,
        'hp_base' => 600,
        'attack_base' => 180,
        'defense_base' => 90,
        'experience_base' => 600,
    ],
    [
        'name' => '神将',
        'type' => 'elite',
        'level' => 55,
        'hp_base' => 1500,
        'attack_base' => 220,
        'defense_base' => 120,
        'experience_base' => 1000,
    ],
    [
        'name' => '神官',
        'type' => 'elite',
        'level' => 58,
        'hp_base' => 1300,
        'attack_base' => 240,
        'defense_base' => 100,
        'experience_base' => 1100,
    ],
    [
        'name' => '神王化身',
        'type' => 'boss',
        'level' => 60,
        'hp_base' => 5000,
        'attack_base' => 300,
        'defense_base' => 150,
        'experience_base' => 3500,
    ],
    [
        'name' => '审判天使',
        'type' => 'elite',
        'level' => 62,
        'hp_base' => 1800,
        'attack_base' => 280,
        'defense_base' => 140,
        'experience_base' => 1300,
    ],
    [
        'name' => '永恒守护者',
        'type' => 'normal',
        'level' => 65,
        'hp_base' => 800,
        'attack_base' => 260,
        'defense_base' => 130,
        'experience_base' => 800,
    ],
    [
        'name' => '时空裂隙',
        'type' => 'normal',
        'level' => 70,
        'hp_base' => 1000,
        'attack_base' => 300,
        'defense_base' => 150,
        'experience_base' => 1000,
    ],
    [
        'name' => '永恒战士',
        'type' => 'elite',
        'level' => 72,
        'hp_base' => 2500,
        'attack_base' => 380,
        'defense_base' => 200,
        'experience_base' => 1800,
    ],
    [
        'name' => '永恒法师',
        'type' => 'elite',
        'level' => 75,
        'hp_base' => 2200,
        'attack_base' => 420,
        'defense_base' => 180,
        'experience_base' => 2000,
    ],
    [
        'name' => '永恒之王',
        'type' => 'boss',
        'level' => 78,
        'hp_base' => 8000,
        'attack_base' => 500,
        'defense_base' => 250,
        'experience_base' => 6000,
    ],
    [
        'name' => '永恒骑士',
        'type' => 'elite',
        'level' => 80,
        'hp_base' => 3000,
        'attack_base' => 450,
        'defense_base' => 230,
        'experience_base' => 2400,
    ],
    [
        'name' => '混沌精灵',
        'type' => 'normal',
        'level' => 82,
        'hp_base' => 1400,
        'attack_base' => 400,
        'defense_base' => 200,
        'experience_base' => 1400,
    ],
    [
        'name' => '虚空领主',
        'type' => 'normal',
        'level' => 85,
        'hp_base' => 1800,
        'attack_base' => 450,
        'defense_base' => 220,
        'experience_base' => 1800,
    ],
    [
        'name' => '混沌战士',
        'type' => 'elite',
        'level' => 88,
        'hp_base' => 4000,
        'attack_base' => 550,
        'defense_base' => 280,
        'experience_base' => 3200,
    ],
    [
        'name' => '混沌魔神',
        'type' => 'elite',
        'level' => 92,
        'hp_base' => 5000,
        'attack_base' => 650,
        'defense_base' => 320,
        'experience_base' => 4000,
    ],
    [
        'name' => '混沌之源',
        'type' => 'boss',
        'level' => 96,
        'hp_base' => 15000,
        'attack_base' => 800,
        'defense_base' => 400,
        'experience_base' => 10000,
    ],
    [
        'name' => '混沌之王',
        'type' => 'boss',
        'level' => 100,
        'hp_base' => 25000,
        'attack_base' => 1000,
        'defense_base' => 500,
        'experience_base' => 20000,
    ],
];

$assetKeys = [
    'wild-boar',
    'wild-wolf',
    'forest-goblin',
    'giant-alpha-wolf',
    'treant-elder',
    'wild-boar-king',
    'cave-bat',
    'cave-spider',
    'skeleton-soldier',
    'skeleton-mage',
    'bone-king',
    'giant-spider',
    'small-demon-imp',
    'fire-elemental',
    'hell-knight',
    'hell-demon-king',
    'fire-demon',
    'demon-wizard',
    'abyss-worm',
    'shadow-ghost',
    'void-walker',
    'abyss-lord',
    'angel-guardian',
    'seraph',
    'archangel',
    'fallen-angel',
    'archangel-chief',
    'temple-knight',
    'divine-servant',
    'divine-messenger',
    'divine-general',
    'divine-priest',
    'god-king-avatar',
    'judgment-angel',
    'eternal-guardian',
    'time-space-rift-creature',
    'eternal-warrior',
    'eternal-mage',
    'eternal-king',
    'eternal-knight',
    'chaos-sprite',
    'void-lord',
    'chaos-warrior',
    'chaos-demon-god',
    'chaos-origin',
    'chaos-king',
];

return array_map(
    fn (array $monster, int $index) => array_merge($monster, [
        'asset_key' => $assetKeys[$index],
    ]),
    $monsters,
    array_keys($monsters)
);
