<?php

// 法师职业技能，由 php artisan game:export-seeder-definitions 从数据库导出，供 GameSeeder 使用
return [
    [
        'name' => '火球术',
        'effect_key' => 'fireball',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 2,
        'skill_points_cost' => 1,
        'effects' => [],
        'description' => '发射火球，造成魔法伤害',
    ],
    [
        'name' => '冰箭',
        'effect_key' => 'ice-arrow',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 5,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [],
        'description' => '发射冰箭造成 100%魔法伤害',
    ],
    [
        'name' => '烈焰风暴',
        'effect_key' => 'meteor-storm',
        'prerequisite_effect_key' => 'fireball',
        'type' => 'active',
        'class_restriction' => 'mage',
        'branch' => 'fire',
        'tier' => 3,
        'mana_cost' => 50,
        'cooldown' => 15,
        'skill_points_cost' => 2,
        'max_level' => 10,
        'base_damage' => 200,
        'damage_per_level' => 5,
        'mana_cost_per_level' => 0,
        'effects' => [],
        'target_type' => 'all',
        'description' => '召唤火焰风暴攻击所有敌人',
    ],
    [
        'name' => '冰霜新星',
        'effect_key' => 'frost-nova',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 20,
        'cooldown' => 5,
        'skill_points_cost' => 2,
        'effects' => [],
        'target_type' => 'all',
        'description' => '释放冰霜，造成范围伤害',
    ],
    [
        'name' => '冰河世纪',
        'effect_key' => 'ice-age',
        'type' => 'active',
        'class_restriction' => 'mage',
        'branch' => 'ice',
        'tier' => 3,
        'mana_cost' => 60,
        'cooldown' => 20,
        'skill_points_cost' => 2,
        'max_level' => 10,
        'base_damage' => 300,
        'damage_per_level' => 10,
        'mana_cost_per_level' => 0,
        'effects' => [],
        'target_type' => 'all',
        'description' => '冰冻所有敌人并造成大量伤害',
    ],
    [
        'name' => '魔力涌动',
        'effect_key' => 'mana-surge',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'mana_bonus' => 20,
        ],
        'description' => '被动提升法力上限',
    ],
    [
        'name' => '雷击',
        'effect_key' => 'lightning',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 25,
        'cooldown' => 4,
        'skill_points_cost' => 2,
        'effects' => [],
        'description' => '召唤闪电，瞬间造成高额伤害',
    ],
    [
        'name' => '连锁闪电',
        'effect_key' => 'chain-lightning',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 20,
        'cooldown' => 6,
        'skill_points_cost' => 1,
        'effects' => [],
        'target_type' => 'all',
        'description' => '闪电在敌人之间弹跳',
    ],
    [
        'name' => '雷霆万钧',
        'effect_key' => 'thunder-wrath',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 60,
        'cooldown' => 18,
        'skill_points_cost' => 2,
        'effects' => [],
        'target_type' => 'all',
        'description' => '召唤巨型雷电攻击所有敌人',
    ],
    [
        'name' => '魔法护盾',
        'effect_key' => 'shield',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 35,
        'cooldown' => 15,
        'skill_points_cost' => 2,
        'effects' => [
            'shield' => 100,
            'duration' => 8,
        ],
        'description' => '用法力值吸收伤害',
    ],
    [
        'name' => '奥术智慧',
        'effect_key' => 'arcane-wisdom',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 2,
        'effects' => [
            'spell_power_bonus' => 15,
        ],
        'description' => '被动提升魔法攻击力',
    ],
    [
        'name' => '陨石术',
        'effect_key' => 'meteor',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 60,
        'cooldown' => 12,
        'skill_points_cost' => 4,
        'effects' => [],
        'target_type' => 'all',
        'description' => '召唤陨石从天而降',
    ],
];
