<?php

// 通用职业技能，由 php artisan game:export-seeder-definitions 从数据库导出，供 GameSeeder 使用
return [
    [
        'name' => '治疗术',
        'effect_key' => 'heal',
        'type' => 'active',
        'class_restriction' => 'all',
        'mana_cost' => 20,
        'cooldown' => 8,
        'skill_points_cost' => 1,
        'effects' => [
            'heal' => true,
        ],
        'description' => '恢复生命值',
    ],
    [
        'name' => '力量强化',
        'effect_key' => 'strength-boost',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'strength_bonus' => 2,
        ],
        'description' => '被动提升力量',
    ],
    [
        'name' => '敏捷强化',
        'effect_key' => 'agility-boost',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'dexterity_bonus' => 2,
        ],
        'description' => '被动提升敏捷',
    ],
    [
        'name' => '体力强化',
        'effect_key' => 'vitality-boost',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'vitality_bonus' => 2,
        ],
        'description' => '被动提升体力',
    ],
    [
        'name' => '能量强化',
        'effect_key' => 'energy-boost',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'energy_bonus' => 2,
        ],
        'description' => '被动提升能量',
    ],
    [
        'name' => '吸血',
        'effect_key' => 'life-steal',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 2,
        'effects' => [
            'life_steal' => 0.05,
        ],
        'description' => '攻击时回复生命值',
    ],
    [
        'name' => '回蓝',
        'effect_key' => 'mana-regen',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 2,
        'effects' => [
            'mana_regen' => 2,
        ],
        'description' => '被动回复法力值',
    ],
    [
        'name' => 'HP 强化',
        'effect_key' => 'hp-boost',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'max_hp_bonus' => 50,
        ],
        'description' => '被动提升最大生命值',
    ],
    [
        'name' => 'MP 强化',
        'effect_key' => 'mp-boost',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'max_mana_bonus' => 30,
        ],
        'description' => '被动提升最大法力值',
    ],
];
