<?php

return [
    'initial_cash' => 800_000,
    'start_bonus' => 2_000_000,
    'max_players' => 8,
    'max_houses_per_property' => 5,
    'max_houses_per_build_action' => 2,
    'jail_position' => 10,
    'board' => [
        ['index' => 0, 'type' => 'start', 'name' => '起点', 'icon' => '🏁'],
        ['index' => 1, 'type' => 'city', 'name' => '罗马', 'price' => 180_000, 'rent' => 28_000, 'house_price' => 90_000, 'color' => '#d64f45'],
        ['index' => 2, 'type' => 'chance', 'name' => '机会', 'icon' => '？'],
        ['index' => 3, 'type' => 'city', 'name' => '雅典', 'price' => 200_000, 'rent' => 32_000, 'house_price' => 100_000, 'color' => '#d64f45'],
        ['index' => 4, 'type' => 'rail', 'name' => '中央铁路', 'price' => 220_000, 'rent' => 35_000, 'icon' => '🚆'],
        ['index' => 5, 'type' => 'city', 'name' => '巴黎', 'price' => 240_000, 'rent' => 38_000, 'house_price' => 120_000, 'color' => '#e0a83a'],
        ['index' => 6, 'type' => 'welfare', 'name' => '公益福利', 'icon' => '❤'],
        ['index' => 7, 'type' => 'city', 'name' => '伦敦', 'price' => 280_000, 'rent' => 44_000, 'house_price' => 140_000, 'color' => '#e0a83a'],
        ['index' => 8, 'type' => 'air', 'name' => '国际航空', 'price' => 300_000, 'rent' => 45_000, 'icon' => '✈'],
        ['index' => 9, 'type' => 'city', 'name' => '纽约', 'price' => 320_000, 'rent' => 52_000, 'house_price' => 160_000, 'color' => '#4f7bd9'],
        ['index' => 10, 'type' => 'jail', 'name' => '监狱', 'icon' => '🔒'],
        ['index' => 11, 'type' => 'city', 'name' => '东京', 'price' => 360_000, 'rent' => 58_000, 'house_price' => 180_000, 'color' => '#4f7bd9'],
        ['index' => 12, 'type' => 'chance', 'name' => '机会', 'icon' => '？'],
        ['index' => 13, 'type' => 'city', 'name' => '首尔', 'price' => 380_000, 'rent' => 62_000, 'house_price' => 190_000, 'color' => '#5aa469'],
        ['index' => 14, 'type' => 'rail', 'name' => '海岸铁路', 'price' => 220_000, 'rent' => 35_000, 'icon' => '🚆'],
        ['index' => 15, 'type' => 'city', 'name' => '新加坡', 'price' => 420_000, 'rent' => 68_000, 'house_price' => 210_000, 'color' => '#5aa469'],
        ['index' => 16, 'type' => 'welfare', 'name' => '公益福利', 'icon' => '❤'],
        ['index' => 17, 'type' => 'city', 'name' => '迪拜', 'price' => 460_000, 'rent' => 76_000, 'house_price' => 230_000, 'color' => '#a45fb4'],
        ['index' => 18, 'type' => 'air', 'name' => '洲际航空', 'price' => 300_000, 'rent' => 45_000, 'icon' => '✈'],
        ['index' => 19, 'type' => 'city', 'name' => '悉尼', 'price' => 500_000, 'rent' => 84_000, 'house_price' => 250_000, 'color' => '#a45fb4'],
    ],
    'chance_cards' => [
        ['code' => 'bonus', 'title' => '项目分红', 'description' => '获得 300K', 'action' => 'cash', 'amount' => 300_000],
        ['code' => 'tax', 'title' => '临时税单', 'description' => '支付 180K', 'action' => 'cash', 'amount' => -180_000],
        ['code' => 'go_start', 'title' => '快速通道', 'description' => '前往起点并领取奖励', 'action' => 'move_to', 'position' => 0, 'grant_start_bonus' => true],
        ['code' => 'go_jail', 'title' => '违规施工', 'description' => '进入监狱', 'action' => 'jail'],
        ['code' => 'move_forward', 'title' => '顺风车', 'description' => '前进 3 格', 'action' => 'move_steps', 'steps' => 3],
    ],
    'welfare_cards' => [
        ['code' => 'community_bonus', 'title' => '公益基金', 'description' => '获得 220K', 'action' => 'cash', 'amount' => 220_000],
        ['code' => 'repair', 'title' => '城市维护', 'description' => '支付 80K', 'action' => 'cash', 'amount' => -80_000],
        ['code' => 'jail_free', 'title' => '法律援助', 'description' => '获得出狱卡', 'action' => 'jail_card'],
        ['code' => 'go_start', 'title' => '志愿者专车', 'description' => '回到起点并领取奖励', 'action' => 'move_to', 'position' => 0, 'grant_start_bonus' => true],
    ],
];
