<?php

// 英语六级词汇，供 CET46WordSeeder 使用
$words = [
    'abase', 'abash', 'abate', 'abbey', 'abbot', 'abbreviate', 'abdicate', 'abdomen', 'abduct', 'aberrant',
    'abet', 'abhor', 'abide', 'abject', 'abjure', 'ablaze', 'abnormality', 'abolition', 'abominable', 'aboriginal',
    'abort', 'abreast', 'abridge', 'abridgment', 'abruptly', 'abscond', 'absolve', 'abstain', 'abstinence', 'abstraction',
    'abstruse', 'absurdity', 'acclaimed', 'accolade', 'accomplice', 'accountability', 'accredit', 'accrue', 'accusation', 'acerbic',
    'acknowledge', 'acme', 'acoustic', 'acquiesce', 'acquittal', 'acrimonious', 'acronym', 'acuity', 'adage', 'adamant',
    'addendum', 'addictive', 'adept', 'adherent', 'adjoin', 'adjourn', 'adjunct', 'admonish', 'admonition', 'ado',
    'adoration', 'adorn', 'adrift', 'adroit', 'adulation', 'adulterate', 'advent', 'adversary', 'adversity', 'advocacy',
    'aesthetic', 'affable', 'affectation', 'affidavit', 'affiliation', 'affinity', 'affirmation', 'afflict', 'affluence', 'affluent',
    'affront', 'aftermath', 'aggrandize', 'aggregate', 'aggression', 'aghast', 'agile', 'agility', 'agitate', 'agitation',
    'agnostic', 'agrarian', 'aide', 'ailment', 'ajar', 'akin', 'alacrity', 'albeit', 'alchemy', 'alcove',
    'alias', 'alibi', 'alienate', 'align', 'alignment', 'alimony', 'allay', 'allegation', 'allege', 'allegiance',
    'allegory', 'alleviate', 'allot', 'allotment', 'alloy', 'allude', 'allure', 'allusion', 'almanac', 'aloft',
    'aloof', 'alpine', 'alteration', 'altercation', 'alternate', 'altitude', 'altruism', 'alumnus', 'amalgamate', 'amass',
    'ambiguity', 'ambivalence', 'amble', 'ambulatory', 'ameliorate', 'amenable', 'amend', 'amenity', 'amiable', 'amicable',
    'amiss', 'amnesia', 'amnesty', 'amorphous', 'ample', 'amplify', 'amputate', 'amulet', 'anachronism', 'analgesic',
    'analogous', 'analogy', 'anarchist', 'anarchy', 'anatomy', 'ancestry', 'anecdote', 'anemia', 'anesthetic', 'anguished',
    'angular', 'animate', 'animosity', 'annex', 'annihilate', 'annotate', 'annuity', 'annul', 'anomaly', 'anonymity',
    'antagonism', 'antagonist', 'ante', 'antecedent', 'anthem', 'anthology', 'anthropology', 'antibody', 'antic', 'anticipation',
    'antidote', 'antipathy', 'antiquated', 'antiseptic', 'antithesis', 'anvil', 'apathy', 'aperture', 'apex', 'aplomb',
    'apocalypse', 'apocryphal', 'apogee', 'appall', 'apparel', 'apparition', 'appease', 'append', 'appendix', 'appertain',
    'appliance', 'applicability', 'appraisal', 'appreciable', 'apprehend', 'apprehension', 'apprehensive', 'apprentice', 'apprise', 'approbation',
    'appropriation', 'aptitude', 'aquatic', 'arable', 'arbiter', 'arbitrary', 'arbitrate', 'arbor', 'arc', 'arcade',
    'arcane', 'arch', 'archaeology', 'archaic', 'archer', 'archetype', 'archipelago', 'archive', 'ardent', 'ardor',
    'arduous', 'arena', 'aristocracy', 'aristocrat', 'ark', 'armada', 'armament', 'armistice', 'armor', 'aroma',
    'aromatic', 'arraign', 'array', 'arrears', 'arrogance', 'arsenal', 'arson', 'articulate', 'artifact', 'artifice',
    'artillery', 'artisan', 'ascertain', 'ascetic', 'ascribe', 'aseptic', 'askew', 'aspersion', 'asphalt', 'asphyxiate',
    'aspirant', 'aspiration', 'aspire', 'assail', 'assassinate', 'assault', 'assemblage', 'assent', 'assertion', 'assessor',
    'assiduous', 'assimilate', 'assuage', 'asteroid', 'asthma', 'astigmatism', 'astound', 'astray', 'astringent', 'astute',
    'asylum', 'atheist', 'atone', 'atrocious', 'atrocity', 'atrophy', 'attain', 'attainment', 'attest', 'attire',
    'audacious', 'audacity', 'audible', 'audition', 'auditor', 'auditorium', 'augment', 'augur', 'aura', 'aural',
    'auspicious', 'austere', 'austerity', 'authenticate', 'authoritarian', 'authoritative', 'autism', 'autocrat', 'automaton', 'autopsy',
    'auxiliary', 'avalanche', 'avarice', 'avenge', 'averse', 'aversion', 'avert', 'aviary', 'aviation', 'avid',
    'avocation', 'await', 'awning', 'awry', 'axiom',
    'babble', 'backlash', 'backlog', 'bacterium', 'baffle', 'bait', 'ballad', 'ballast', 'bane', 'banish',
    'banquet', 'banter', 'baptism', 'baptize', 'barb', 'barbaric', 'barbarous', 'barley', 'barometer', 'baron',
    'baroque', 'barracks', 'barrage', 'barren', 'barricade', 'barter', 'basalt', 'bash', 'bask', 'bass',
    'bastard', 'batch', 'baton', 'battalion', 'bauble', 'bazaar', 'beacon', 'bead', 'beam', 'bearing',
    'beckon', 'bedrock', 'befriend', 'beguile', 'behest', 'behold', 'belie', 'believer', 'belittle', 'bellicose',
    'belligerent', 'bellow', 'bemoan', 'benchmark', 'benediction', 'benefactor', 'beneficiary', 'benevolent', 'benign', 'bequeath',
    'bequest', 'berate', 'bereave', 'bereft', 'berserk', 'beseech', 'beset', 'besiege', 'besmirch', 'bestow',
    'betray', 'betroth', 'beverage', 'bewilder', 'bicameral', 'bicker', 'biennial', 'bigot', 'bigotry', 'bilateral',
    'bilingual', 'billboard', 'binge', 'biodegradable', 'biosphere', 'bipartisan', 'bisect', 'bizarre', 'blackmail', 'blaspheme',
    'blasphemy', 'blatant', 'blaze', 'bleach', 'bleak', 'blemish', 'blight', 'bliss', 'blithe', 'blizzard',
    'bloat', 'blockade', 'blockbuster', 'bloodshed', 'blot', 'blueprint', 'bluff', 'blunder', 'blunt', 'blur',
    'blurt', 'blush', 'bode', 'bog', 'boggle', 'bogus', 'boisterous', 'bolster', 'bombardment', 'bombast',
    'bonanza', 'bondage', 'bonfire', 'boon', 'boor', 'bootleg', 'booty', 'borderline', 'botch', 'bough',
    'boulder', 'boulevard', 'bounty', 'bout', 'brace', 'bracing', 'bracket', 'brag', 'brandish', 'bravado',
    'brawl', 'brazen', 'breach', 'breadwinner', 'breakup', 'brethren', 'brevity', 'bribe', 'bribery', 'brigade',
    'brim', 'brine', 'brink', 'bristle', 'brittle', 'broach', 'brochure', 'broker', 'brood', 'browse',
    'brunt', 'brusque', 'brutality', 'brute', 'buckle', 'budge', 'buffer', 'buffet', 'bulge', 'bulky',
    'bulldoze', 'bumble', 'bumpy', 'bungle', 'buoyant', 'bureaucrat', 'burgeon', 'burglar', 'burglary', 'burlesque',
    'burnish', 'burrow', 'bust', 'bustle', 'buttress', 'bypass', 'bystander',
    'cabal', 'cache', 'cacophony', 'cadaver', 'cadence', 'cadet', 'cajole', 'calamity', 'caliber', 'calibrate',
    'callous', 'callow', 'camouflage', 'candid', 'candor', 'canine', 'canker', 'cannibal', 'canopy', 'cant',
    'canteen', 'canter', 'canvass', 'capacious', 'cape', 'capillary', 'capitulate', 'capricious', 'captivate', 'captive',
    'captivity', 'carat', 'carcass', 'carcinogen', 'cardinal', 'careen', 'caress', 'caricature', 'carnage', 'carnal',
    'carnivore', 'carol', 'carousel', 'carp', 'cartography', 'cascade', 'caste', 'castigate', 'casualty', 'cataclysm',
    'catalyst', 'catapult', 'cataract', 'catastrophe', 'categorical', 'cater', 'catharsis', 'catholic', 'caucus', 'cauldron',
    'causal', 'caustic', 'cauterize', 'cavalier', 'cavalry', 'caveat', 'cavern', 'cavity', 'cede', 'celestial',
    'celibacy', 'censor', 'censure', 'centennial', 'centralize', 'centrifugal', 'cerebral', 'ceremonial', 'cessation', 'chafe',
    'chaff', 'chagrin', 'chalet', 'chalice', 'chameleon', 'chancellor', 'chandelier', 'chant', 'chaotic', 'chapel',
    'chaperone', 'char', 'charade', 'chariot', 'charisma', 'charitable', 'charlatan', 'charter', 'chary', 'chasm',
    'chassis', 'chaste', 'chasten', 'chastise', 'chatter', 'chauvinist', 'cherish', 'cherub', 'chicanery', 'chide',
    'chiefly', 'chieftain', 'chiffon', 'chilly', 'chime', 'chisel', 'chivalry', 'chlorine', 'choke', 'cholera',
    'cholesterol', 'chord', 'chore', 'choreography', 'chortle', 'chromatic', 'chromosome', 'chronic', 'chronicle', 'chronological',
    'chubby', 'chuckle', 'chunk', 'churn', 'cider', 'cinch', 'cipher', 'circuitous', 'circumference', 'circumscribe',
    'circumspect', 'circumstantial', 'circumvent', 'cistern', 'citadel', 'citation', 'civic', 'civility', 'clad', 'clamber',
    'clammy', 'clamor', 'clamp', 'clandestine', 'clang', 'clank', 'clap', 'clarification', 'clarion', 'classification',
    'clause', 'cleanse', 'clearance', 'cleavage', 'cleave', 'cleft', 'clemency', 'clench', 'clergy', 'clerical',
    'clientele', 'climactic', 'clinch', 'clinical', 'clique', 'cloak', 'clog', 'cloister', 'clot', 'clout',
    'clown', 'cloy', 'coagulate', 'coalesce', 'coalition', 'coax', 'cobble', 'cocky', 'coddle', 'codify',
    'coerce', 'coercion', 'coexist', 'coffer', 'cogent', 'cogitate', 'cognition', 'cognitive', 'cognizant', 'cohabit',
    'cohere', 'coherence', 'cohesion', 'cohesive', 'cohort', 'coincidental', 'collaborate', 'collaboration', 'collaborative', 'collage',
    'collateral', 'colloquial', 'colloquium', 'collusion', 'colossal', 'coma', 'comatose', 'combatant', 'combustible', 'combustion',
    'comeback', 'comedian', 'comedic', 'comely', 'comet', 'comeuppance', 'commemorate', 'commencement', 'commend', 'commendable',
    'commensurate', 'commentary', 'commentator', 'commissary', 'commissioner', 'commit', 'commonwealth', 'commotion', 'communal', 'commune',
    'communicable', 'communion', 'commute', 'compact', 'compassion', 'compassionate', 'compatible', 'compatriot', 'compel', 'compelling',
    'compendium', 'competence', 'compile', 'complacency', 'complacent', 'complement', 'complementary', 'complexion', 'compliant', 'complication',
    'complicit', 'compliment', 'complimentary', 'comply', 'composite', 'compost', 'composure', 'comprehend', 'comprehension', 'compress',
    'compression', 'compulsion', 'compulsive', 'compunction', 'computation', 'comrade', 'concave', 'conceal', 'concede', 'conceit',
    'conceited', 'conceivable', 'concentrated', 'concentric', 'conceptual', 'concerted', 'concession', 'concierge', 'conciliatory', 'concise',
    'conclave', 'conclusive', 'concoct', 'concomitant', 'concord', 'concordance', 'concourse', 'concur', 'concurrent', 'concussion',
    'condemnation', 'condensation', 'condense', 'condescend', 'condescending', 'condiment', 'conditional', 'condolence', 'condone', 'conducive',
    'conduit', 'confederate', 'confer', 'conferee', 'confide', 'confidential', 'configuration', 'confine', 'confirmation', 'confiscate',
    'conflagration', 'confluence', 'conformist', 'conformity', 'confound', 'confront', 'confrontation', 'congeal', 'congenial', 'congenital',
    'congest', 'congestion', 'conglomerate', 'congratulation', 'congregate', 'congregation', 'congressional', 'congruent', 'conifer', 'conjecture',
];

return array_map(fn ($w) => ['content' => $w, 'meaning' => ''], array_unique($words));
