<?php

// 初中英语词汇，供 CET46WordSeeder 使用
$words = [
    // 动词扩展
    'accept', 'achieve', 'act', 'add', 'admit', 'advise', 'afford', 'agree', 'allow', 'appear',
    'apply', 'argue', 'arrange', 'arrive', 'attack', 'attend', 'attract', 'avoid', 'beat', 'become',
    'believe', 'belong', 'blow', 'borrow', 'bother', 'build', 'burn', 'call', 'care', 'cause',
    'celebrate', 'change', 'charge', 'chase', 'check', 'choose', 'claim', 'clear', 'collect', 'combine',
    'comfort', 'communicate', 'compare', 'compete', 'complain', 'complete', 'concern', 'conclude', 'confirm', 'connect',
    'consider', 'contain', 'continue', 'control', 'convince', 'copy', 'correct', 'count', 'cover', 'create',
    'cross', 'cry', 'damage', 'deal', 'decide', 'declare', 'decorate', 'decrease', 'defend', 'delay',
    'deliver', 'demand', 'depend', 'describe', 'design', 'desire', 'destroy', 'determine', 'develop', 'die',
    'dig', 'direct', 'disappear', 'discover', 'discuss', 'divide', 'doubt', 'dream', 'dress', 'earn',
    'enable', 'encourage', 'enjoy', 'enter', 'escape', 'examine', 'exchange', 'excite', 'exist', 'expect',
    'experience', 'experiment', 'explain', 'explore', 'express', 'extend', 'face', 'fail', 'fall', 'fear',
    'feel', 'fight', 'fill', 'fit', 'flow', 'focus', 'follow', 'force', 'form', 'gain',
    'gather', 'generate', 'grab', 'graduate', 'greet', 'grow', 'guard', 'guess', 'guide', 'hang',
    'happen', 'hide', 'hope', 'hunt', 'hurt', 'identify', 'ignore', 'imagine', 'improve', 'include',
    'increase', 'indicate', 'influence', 'inform', 'insist', 'inspire', 'intend', 'introduce', 'invent', 'invite',
    'involve', 'join', 'judge', 'kill', 'knock', 'lack', 'land', 'last', 'laugh', 'lay',
    'lead', 'leave', 'lend', 'let', 'lift', 'limit', 'link', 'list', 'live', 'load',
    'lock', 'manage', 'mark', 'match', 'matter', 'measure', 'meet', 'mention', 'mind', 'miss',
    'mix', 'move', 'notice', 'obtain', 'occur', 'offer', 'operate', 'order', 'organize', 'own',
    'pack', 'park', 'pass', 'perform', 'permit', 'persuade', 'place', 'plan', 'point', 'pollute',
    'post', 'pour', 'practice', 'praise', 'predict', 'prefer', 'prepare', 'present', 'press', 'pretend',
    'prevent', 'print', 'produce', 'promise', 'pronounce', 'protect', 'prove', 'provide', 'publish', 'punish',
    'purchase', 'pursue', 'raise', 'reach', 'react', 'realize', 'receive', 'recognize', 'recommend', 'record',
    'recover', 'reduce', 'reflect', 'refuse', 'regard', 'regret', 'relate', 'relax', 'release', 'remain',
    'remind', 'remove', 'repair', 'repeat', 'replace', 'reply', 'report', 'represent', 'request', 'require',
    'research', 'respect', 'respond', 'rest', 'return', 'reveal', 'review', 'rise', 'risk', 'roll',
    'rush', 'satisfy', 'scare', 'search', 'seat', 'seem', 'select', 'send', 'sense', 'separate',
    'serve', 'set', 'settle', 'shake', 'shape', 'share', 'shine', 'shock', 'shoot', 'shout',
    'show', 'shut', 'sign', 'signal', 'sink', 'smell', 'smile', 'solve', 'sort', 'sound',
    'spare', 'spell', 'split', 'spread', 'steal', 'stick', 'store', 'strike', 'struggle', 'succeed',
    'suffer', 'suggest', 'suit', 'supply', 'support', 'suppose', 'surprise', 'surround', 'survive', 'suspect',
    'sweep', 'swing', 'switch', 'target', 'test', 'thank', 'threaten', 'tie', 'touch', 'track',
    'train', 'transfer', 'translate', 'trap', 'treat', 'trick', 'trust', 'type', 'unite', 'update',
    'upset', 'urge', 'value', 'vary', 'view', 'vote', 'warn', 'waste', 'weigh', 'win',
    'wish', 'wonder', 'worry', 'wrap', 'yell',
    // 名词扩展
    'ability', 'accident', 'account', 'achievement', 'action', 'activity', 'addition', 'address', 'adult', 'advantage',
    'adventure', 'advertisement', 'advice', 'affair', 'affect', 'age', 'agreement', 'aim', 'alarm', 'album',
    'amount', 'ancestor', 'anger', 'angle', 'announcement', 'anxiety', 'apartment', 'appearance', 'application', 'appointment',
    'area', 'argument', 'army', 'arrangement', 'arrival', 'article', 'artist', 'aspect', 'assignment', 'assistant',
    'association', 'atmosphere', 'attention', 'attitude', 'audience', 'author', 'authority', 'average', 'award', 'background',
    'balance', 'band', 'base', 'basis', 'battle', 'beauty', 'beginning', 'behavior', 'belief', 'benefit',
    'birth', 'blank', 'block', 'blood', 'board', 'bomb', 'bone', 'border', 'boss', 'bottom',
    'brain', 'branch', 'brand', 'breath', 'brick', 'bridge', 'broadcast', 'budget', 'building', 'bullet',
    'burden', 'bus', 'bush', 'business', 'cable', 'camera', 'camp', 'campaign', 'cancer', 'candidate',
    'capital', 'captain', 'career', 'carpet', 'cartoon', 'case', 'cash', 'cast', 'castle', 'cause',
    'ceiling', 'cell', 'century', 'ceremony', 'chain', 'chair', 'challenge', 'champion', 'chance', 'channel',
    'chapter', 'character', 'charge', 'charity', 'chart', 'check', 'chest', 'childhood', 'choice', 'circle',
    'circuit', 'citizen', 'claim', 'climate', 'clinic', 'cloth', 'clothes', 'cloud', 'club', 'clue',
    'coach', 'coal', 'coast', 'code', 'coin', 'collection', 'college', 'colony', 'column', 'comedy',
    'comment', 'committee', 'communication', 'community', 'companion', 'company', 'comparison', 'competition', 'complaint', 'complex',
    'computer', 'concentration', 'concept', 'concern', 'conclusion', 'condition', 'conference', 'confidence', 'conflict', 'confusion',
    'connection', 'consequence', 'consideration', 'construction', 'contact', 'content', 'contest', 'context', 'contract', 'contrast',
    'contribution', 'control', 'conversation', 'cook', 'cookie', 'copy', 'corner', 'cost', 'cottage', 'cotton',
    'council', 'counter', 'country', 'couple', 'courage', 'course', 'court', 'cousin', 'cover', 'cow',
    'crash', 'cream', 'creation', 'creature', 'credit', 'crime', 'criminal', 'crisis', 'criticism', 'crop',
    'crowd', 'crown', 'culture', 'cup', 'cure', 'curiosity', 'currency', 'custom', 'customer', 'cycle',
    // 形容词扩展
    'absent', 'abstract', 'academic', 'acceptable', 'accessible', 'accurate', 'active', 'actual', 'additional', 'adequate',
    'advanced', 'afraid', 'aggressive', 'alive', 'alone', 'amazing', 'ancient', 'annoyed', 'annual', 'anxious',
    'apparent', 'appropriate', 'artificial', 'ashamed', 'asleep', 'attractive', 'available', 'average', 'aware', 'awful',
    'backward', 'bare', 'basic', 'bitter', 'blind', 'bold', 'bored', 'boring', 'brave', 'brief',
    'brilliant', 'broad', 'broken', 'calm', 'capable', 'careful', 'careless', 'casual', 'central', 'certain',
    'cheap', 'chemical', 'chief', 'civil', 'classic', 'classical', 'clever', 'close', 'comfortable', 'common',
    'complete', 'complex', 'concerned', 'confident', 'confused', 'conscious', 'constant', 'contemporary', 'content', 'convenient',
    'cool', 'correct', 'crazy', 'creative', 'critical', 'cruel', 'cultural', 'curious', 'current', 'daily',
    'damp', 'dead', 'deaf', 'dear', 'decent', 'deep', 'definite', 'delicate', 'democratic', 'dependent',
    'desperate', 'detailed', 'determined', 'digital', 'direct', 'dirty', 'disabled', 'disappointed', 'distant', 'distinct',
    'double', 'dramatic', 'drunk', 'dry', 'due', 'dull', 'eager', 'economic', 'educational', 'effective',
    'efficient', 'elderly', 'electric', 'electronic', 'elegant', 'elementary', 'embarrassed', 'emotional', 'empty', 'entire',
    'environmental', 'equal', 'essential', 'even', 'eventual', 'evident', 'evil', 'exact', 'excellent', 'excited',
    'exciting', 'existing', 'expensive', 'experienced', 'expert', 'extra', 'extraordinary', 'extreme', 'fair', 'false',
    'familiar', 'famous', 'fancy', 'fantastic', 'fat', 'fatal', 'favorite', 'federal', 'fellow', 'female',
    'fierce', 'final', 'financial', 'firm', 'fit', 'fixed', 'flat', 'flexible', 'fluent', 'fond',
    'foolish', 'foreign', 'formal', 'former', 'fortunate', 'forward', 'fragile', 'frank', 'free', 'frequent',
    'fresh', 'friendly', 'frightened', 'frustrated', 'fundamental', 'funny', 'further', 'future', 'general', 'generous',
    'gentle', 'genuine', 'giant', 'glad', 'global', 'good', 'gorgeous', 'gradual', 'grand', 'grateful',
    'gray', 'greedy', 'gross', 'growing', 'guilty', 'handsome', 'handy', 'harmful', 'healthy', 'heavy',
    // 副词扩展
    'absolutely', 'accidentally', 'accordingly', 'actually', 'additionally', 'admittedly', 'afterwards', 'almost', 'altogether', 'anyway',
    'apparently', 'approximately', 'automatically', 'badly', 'barely', 'basically', 'briefly', 'broadly', 'carefully', 'certainly',
    'clearly', 'closely', 'commonly', 'completely', 'constantly', 'currently', 'deeply', 'definitely', 'deliberately', 'directly',
    'easily', 'effectively', 'efficiently', 'entirely', 'equally', 'especially', 'essentially', 'eventually', 'exactly', 'extremely',
    'fairly', 'finally', 'firmly', 'firstly', 'formerly', 'fortunately', 'frankly', 'freely', 'frequently', 'fully',
    'generally', 'gently', 'gradually', 'greatly', 'happily', 'hardly', 'heavily', 'highly', 'honestly', 'hopefully',
    'immediately', 'importantly', 'increasingly', 'indeed', 'independently', 'initially', 'instead', 'largely', 'lately', 'lightly',
    'likely', 'literally', 'locally', 'mainly', 'merely', 'mostly', 'naturally', 'nearly', 'necessarily', 'normally',
    'notably', 'obviously', 'occasionally', 'officially', 'originally', 'otherwise', 'partly', 'particularly', 'perfectly', 'permanently',
    'personally', 'physically', 'possibly', 'potentially', 'practically', 'precisely', 'preferably', 'previously', 'primarily', 'probably',
    // 其他词汇
    'abroad', 'absence', 'accent', 'access', 'accommodation', 'accompany', 'according', 'accurate', 'accuse', 'acre',
    'adapt', 'addition', 'adequate', 'adjust', 'administration', 'admire', 'admission', 'adolescent', 'adopt', 'advance',
    'advantage', 'advertise', 'affect', 'affection', 'agency', 'agent', 'agriculture', 'aid', 'AIDS', 'aircraft',
    'airline', 'alcohol', 'alien', 'alliance', 'allocate', 'alongside', 'alternative', 'altogether', 'aluminum', 'amateur',
    'ambassador', 'ambition', 'amendment', 'amid', 'analysis', 'analyze', 'ancient', 'anniversary', 'announce', 'annual',
    'anticipate', 'anxiety', 'apart', 'apologize', 'apparent', 'appeal', 'appetite', 'applause', 'applicable', 'appreciation',
    'approach', 'appropriate', 'approval', 'approximate', 'architect', 'architecture', 'arise', 'arithmetic', 'armed', 'arrangement',
];

return array_map(fn ($w) => ['content' => $w, 'meaning' => ''], array_unique($words));
